version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data:ro
      - ./initDatabase/scheme.sql:/docker-entrypoint-initdb.d/0_scheme.sql:ro
      - ./initDatabase/import.sql:/docker-entrypoint-initdb.d/1_import.sql:ro
    ports:
      - "5432:5432"

volumes:
  pgdata:
